-- Never reads real auth: every test has an explicit temporary store and fake HTTP.
local json = require("dkjson")

describe("OpenAI isolated authentication", function()
    local Auth, Store, path, now, calls, replies, previous_json, previous_storage, default_root
    local jwt = "head.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsiY2hhdGdwdF9hY2NvdW50X2lkIjoiYWNjdC10ZXN0In19.sig"
    local function tokens(refresh)
        return { access_token = jwt, refresh_token = refresh or "fake-rotated", expires_in = 3600 }
    end
    local function respond(status, body, callback)
        replies[#replies + 1] = { status = status, body = body, callback = callback }
    end
    local function start(interval)
        respond(200, { device_auth_id = "fake-device", user_code = "FAKE-CODE", interval = interval or "5" })
        return assert(Auth:startDeviceLogin())
    end
    local function seed(expiry)
        local release = assert(Store:acquire(path))
        assert(Store:save(path, { access_token = jwt, refresh_token = "fake-original",
            account_id = "acct-test", expires_at = expiry or now - 1 }))
        release()
    end
    before_each(function()
        previous_json = package.loaded.json
        previous_storage = package.loaded.datastorage
        default_root = nil
        package.loaded.json = json
        Auth = dofile("xray.koplugin/xray_openai_auth.lua")
        Store = dofile("xray.koplugin/xray_auth_store.lua")
        path = os.tmpname()
        os.remove(path)
        now, calls, replies = 100000, {}, {}
        Auth.store_path, Auth.store = path, Store
        Auth.now = function() return now end
        Auth.http = { request = function(_, url, method, headers, body, timeout)
            calls[#calls + 1] = { url = url, method = method, headers = headers, body = body, timeout = timeout }
            local reply = table.remove(replies, 1)
            assert(reply, "unexpected network call")
            if reply.callback then reply.callback() end
            return true, reply.status, type(reply.body) == "string" and reply.body or json.encode(reply.body), {}
        end }
    end)
    after_each(function()
        if path then
            os.remove(path)
            os.remove(path .. ".lock")
            os.remove(path .. ".tmp")
            os.remove(path .. ".generation")
            os.remove(path .. ".generation.tmp")
            os.remove(path .. ".link")
        end
        if default_root then
            local ffi = require("ffi")
            ffi.cdef[[ int rmdir(const char *); ]]
            ffi.C.rmdir(default_root .. "/settings/xray")
            ffi.C.rmdir(default_root .. "/settings")
            ffi.C.rmdir(default_root)
        end
        package.loaded.datastorage = previous_storage
        package.loaded.json = previous_json
    end)

    it("has no credential or dependency access at module load", function()
        local original = package.loaded.datastorage
        package.loaded.datastorage = { getSettingsDir = function() error("must not read") end }
        local fresh = dofile("xray.koplugin/xray_openai_auth.lua")
        package.loaded.datastorage = original
        assert.is_table(fresh)
        assert.are.equal(0, #calls)
    end)
    it("returns disconnected without network and never exports tokens in status", function()
        assert.are.same({ connected = false }, Auth:getStatus())
        seed()
        assert.are.same({ connected = true, account_id = "acct-test", expires_at = now - 1 }, Auth:getStatus())
        assert.are.equal(0, #calls)
    end)
    it("starts the pinned device protocol with a fixed verification URL", function()
        local flow = start()
        assert.are.equal("https://auth.openai.com/codex/device", flow.verification_uri)
        assert.are.equal(now + 900, flow.expires_at)
        assert.are.equal(5, flow.interval)
        assert.are.equal("https://auth.openai.com/api/accounts/deviceauth/usercode", calls[1].url)
        assert.are.equal("app_EMoamEEZ73f0CkXaXp7hrann", json.decode(calls[1].body).client_id)
        assert.is_nil(flow.access_token)
        assert.is_nil(flow.refresh_token)
    end)
    it("honors pending 403 and 404 responses and polling interval", function()
        local flow = start()
        respond(403, {})
        assert.are.equal("pending", Auth:pollDeviceLogin(flow))
        assert.are.equal("pending", Auth:pollDeviceLogin(flow))
        assert.are.equal(2, #calls)
        now = now + 5
        respond(404, {})
        assert.are.equal("pending", Auth:pollDeviceLogin(flow))
        assert.are.equal(3, #calls)
    end)
    it("honors explicit pending and slowdown including 429", function()
        local flow = start()
        respond(400, { error = "deviceauth_authorization_pending" })
        assert.are.equal("pending", Auth:pollDeviceLogin(flow))
        now = now + 5
        respond(400, { error = { code = "slow_down" } })
        assert.are.equal("slow_down", Auth:pollDeviceLogin(flow))
        assert.are.equal(10, flow.interval)
        now = now + 10
        respond(429, {})
        assert.are.equal("slow_down", Auth:pollDeviceLogin(flow))
        assert.are.equal(15, flow.interval)
    end)
    it("expires locally without another poll", function()
        local flow = start()
        now = flow.expires_at
        assert.are.equal("expired", Auth:pollDeviceLogin(flow))
        assert.are.equal(1, #calls)
    end)
    it("handles server expiration and denial without leaking bodies", function()
        local flow = start()
        respond(400, { error = "expired_token", detail = "fake-secret" })
        assert.are.equal("expired", Auth:pollDeviceLogin(flow))
        flow = start()
        respond(403, { error = "access_denied", detail = "fake-secret" })
        local status, message = Auth:pollDeviceLogin(flow)
        assert.are.equal("denied", status)
        assert.is_nil(message:find("fake-secret", 1, true))
        assert.are.equal("denied", Auth:pollDeviceLogin(flow))
        assert.are.equal(4, #calls)
    end)
    it("rejects cancelled and superseded flows without polling", function()
        local flow = start()
        flow.cancelled = true
        assert.are.equal("error", Auth:pollDeviceLogin(flow))
        flow = start()
        start()
        assert.are.equal("error", Auth:pollDeviceLogin(flow))
        assert.are.equal(3, #calls)
    end)
    it("rejects a late poll callback after cancellation before exchange", function()
        local flow = start()
        respond(200, { authorization_code = "fake-code", code_verifier = "fake-verifier" }, function()
            flow.cancelled = true
        end)
        assert.are.equal("error", Auth:pollDeviceLogin(flow))
        assert.are.equal(2, #calls)
        assert.is_false(Auth:getStatus().connected)
    end)
    it("rejects a late exchange callback after cancellation before storage", function()
        local flow = start()
        respond(200, { authorization_code = "fake-code", code_verifier = "fake-verifier" })
        respond(200, tokens(), function() flow.cancelled = true end)
        assert.are.equal("error", Auth:pollDeviceLogin(flow))
        assert.is_false(Auth:getStatus().connected)
    end)
    it("atomically saves login and returns only the access context", function()
        local flow = start()
        respond(200, { authorization_code = "fake-code", code_verifier = "fake-verifier" })
        respond(200, tokens())
        assert.are.equal("complete", Auth:pollDeviceLogin(flow))
        assert.are.equal("complete", Auth:pollDeviceLogin(flow))
        assert.is_true(calls[3].body:find("grant_type=authorization_code", 1, true) ~= nil)
        assert.is_true(calls[3].body:find("redirect_uri=https%3A%2F%2Fauth.openai.com%2Fdeviceauth%2Fcallback", 1, true) ~= nil)
        local context = assert(Auth:getAccessContext())
        assert.are.equal(jwt, context.access_token)
        assert.are.equal("acct-test", context.account_id)
        assert.is_nil(context.refresh_token)
        assert.are.equal("fake-rotated", Store:load(path).refresh_token)
        assert.is_nil(io.open(path .. ".tmp", "rb"))
    end)
    it("refreshes before expiry and persists rotation before returning", function()
        seed(now + 30)
        respond(200, tokens())
        local context = assert(Auth:getAccessContext())
        assert.are.equal(now + 3600, context.expires_at)
        assert.is_nil(context.refresh_token)
        assert.are.equal("fake-rotated", Store:load(path).refresh_token)
        assert.is_true(calls[1].body:find("refresh_token=fake%-original") ~= nil)
        assert(Auth:getAccessContext())
        assert.are.equal(1, #calls)
    end)
    it("force-refreshes a still-current credential", function()
        seed(now + 3600)
        respond(200, tokens())
        assert(Auth:getAccessContext(true))
        assert.are.equal(1, #calls)
    end)
    it("serializes reentrant refresh and releases locks after success", function()
        seed()
        respond(200, tokens(), function()
            local value, code = Auth:getAccessContext(true)
            assert.is_nil(value)
            assert.are.equal("auth_busy", code)
            local release, lock_code = Store:acquire(path)
            assert.is_nil(release)
            assert.are.equal("auth_busy", lock_code)
        end)
        assert(Auth:getAccessContext())
        local release = assert(Store:acquire(path))
        release()
        assert.are.equal(1, #calls)
    end)
    it("fails closed when an independent descriptor owns the store lock", function()
        seed()
        local release = assert(Store:acquire(path))
        local value, code = Auth:getAccessContext()
        release()
        assert.is_nil(value)
        assert.are.equal("auth_busy", code)
        assert.are.equal(0, #calls)
    end)
    it("persists refresh rotation even if an unrelated UI flow is cancelled", function()
        seed()
        local flow = { cancelled = false }
        respond(200, tokens(), function() flow.cancelled = true end)
        assert(Auth:getAccessContext())
        assert.are.equal("fake-rotated", Store:load(path).refresh_token)
    end)
    it("does not report usable credentials when rotation storage fails", function()
        seed()
        respond(200, tokens())
        Store.save = function() return nil, "store_write_failed" end
        local value, code = Auth:getAccessContext()
        assert.is_nil(value)
        assert.are.equal("store_write_failed", code)
    end)
    it("clears invalid_grant and requires reconnect without a retry", function()
        seed()
        respond(400, { error = "invalid_grant", error_description = "fake-original" })
        local value, code, message = Auth:getAccessContext()
        assert.is_nil(value)
        assert.are.equal("invalid_grant", code)
        assert.is_nil(message:find("fake-original", 1, true))
        assert.is_false(Auth:getStatus().connected)
        assert.are.equal(1, #calls)
    end)
    it("sanitizes thrown transport errors and releases the lock", function()
        seed()
        Auth.http.request = function() error("fake-secret-token") end
        local value, code, message = Auth:getAccessContext()
        assert.is_nil(value)
        assert.are.equal("network_error", code)
        assert.is_nil(message:find("fake-secret-token", 1, true))
        local release = assert(Store:acquire(path))
        release()
    end)
    it("rejects malformed tokens and account claim injection", function()
        seed()
        respond(200, { access_token = "not-a-jwt", refresh_token = "fake-secret", expires_in = 3600 })
        local value, code = Auth:getAccessContext()
        assert.is_nil(value)
        assert.are.equal("invalid_response", code)
        assert.are.equal("fake-original", Store:load(path).refresh_token)
    end)
    it("logs out locally, cancels pending flows and is idempotent", function()
        seed()
        local flow = start()
        assert(Auth:logout())
        assert(Auth:logout())
        assert.is_false(Auth:getStatus().connected)
        assert.is_true(flow.cancelled)
        assert.are.equal(1, #calls)
    end)
    it("removes local tokens even when generation metadata is corrupt", function()
        seed()
        local file = assert(io.open(path .. ".generation", "wb"))
        file:write("invalid-json")
        file:close()
        local ok, code = Auth:logout()
        assert.is_nil(ok)
        assert.are.equal("store_invalid", code)
        assert.is_false(Auth:getStatus().connected)
        assert.is_nil(io.open(path, "rb"))
        assert.are.equal(0, #calls)
    end)
    it("uses verified ARM and x86 open flag mappings", function()
        assert.are.equal(32768, Store:platformFlags("arm").nofollow)
        assert.are.equal(16384, Store:platformFlags("arm").directory)
        assert.are.equal(32768, Store:platformFlags("arm64").nofollow)
        assert.are.equal(131072, Store:platformFlags("x64").nofollow)
        assert.is_false(pcall(Store.platformFlags, Store, "mips"))
    end)
    it("resolves the reader default relative settings directory into the fake root", function()
        default_root = path .. ".root"
        path = default_root .. "/settings/xray/openai_auth.json"
        package.loaded.datastorage = {
            getSettingsDir = function() return "./settings" end,
            getFullDataDir = function() return default_root end,
        }
        Auth.store_path = nil
        local flow = start()
        assert.is_table(flow)
        assert.are.equal(1, Store:load(path .. ".generation").generation)
        assert(Auth:logout())
        assert.is_false(Auth:getStatus().connected)
    end)
    it("increases a server interval longer than sixty seconds on slowdown", function()
        local flow = start(120)
        respond(400, { error = "slow_down" })
        assert.are.equal("slow_down", Auth:pollDeviceLogin(flow))
        assert.are.equal(125, flow.interval)
    end)
    it("invalidates a pending flow when another instance starts a newer login", function()
        local flow = start()
        local other = dofile("xray.koplugin/xray_openai_auth.lua")
        other.store_path, other.store, other.now, other.http = path, Store, Auth.now, Auth.http
        respond(200, { device_auth_id = "new-device", user_code = "NEW-CODE", interval = 5 })
        assert(other:startDeviceLogin())
        assert.are.equal("error", Auth:pollDeviceLogin(flow))
        assert.are.equal(2, #calls)
        assert.is_false(Auth:getStatus().connected)
    end)
    it("prevents a real child-process logout from resurrecting a pending parent login", function()
        local flow = start()
        local ffi = require("ffi")
        ffi.cdef[[ int fork(void); int waitpid(int, int *, int); void _exit(int); ]]
        io.stdout:flush()
        local pid = ffi.C.fork()
        assert(pid >= 0)
        if pid == 0 then
            local other = dofile("xray.koplugin/xray_openai_auth.lua")
            other.store_path, other.store = path, Store
            local ok = other:logout()
            ffi.C._exit(ok and 0 or 1)
        end
        local status = ffi.new("int[1]")
        assert.are.equal(pid, ffi.C.waitpid(pid, status, 0))
        assert.are.equal(0, tonumber(status[0]))
        assert.are.equal("error", Auth:pollDeviceLogin(flow))
        assert.are.equal(1, #calls)
        assert.is_false(Auth:getStatus().connected)
    end)
    it("rejects symlink parents and symlink credential files", function()
        local ffi = require("ffi")
        ffi.cdef[[ int symlink(const char *, const char *); ]]
        assert.are.equal(0, ffi.C.symlink("/tmp", path .. ".link"))
        local release, code = Store:acquire(path .. ".link/xray-auth-test.json")
        assert.is_nil(release)
        assert.are.equal("store_unavailable", code)
        os.remove(path .. ".link")
        seed()
        assert.are.equal(0, ffi.C.symlink(path, path .. ".link"))
        local value, load_code = Store:load(path .. ".link")
        assert.is_nil(value)
        assert.are.equal("store_unavailable", load_code)
    end)
    it("rejects nonabsolute store overrides without file access", function()
        Auth.store_path = "relative-secret.json"
        local value, code = Auth:getAccessContext()
        assert.is_nil(value)
        assert.are.equal("store_unavailable", code)
        assert.are.equal(0, #calls)
    end)
end)
